apiVersion: v1
kind: Service
metadata:
  labels:
    app: gpuquota-controller
  name: gpuquota-controller
  namespace: kube-system
spec:
  ports:
    - name: https
      port: 443
      protocol: "TCP"
  selector:
    app: gpuquota-controller
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gpuquota-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: gpuquota-controller
    spec:
      containers:
        - name: gpuquota-controller
          image: "xychu/throttle-controller:v1"
          #imagePullPolicy: Always
          args:
            - "-logtostderr"
            - "-v=4"
