apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: gpuquota-webhook-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webhook-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
