apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    resources:
        limits:
            nvidia.com/gpu: 5
    ports:
    - containerPort: 80
